version: '3.8'
services:
  vproweb:
    build:
      context: ./Docker-files/web
    image: oppytms/vproweb
    ports:
      - "80:80"
    depends_on:
      - vproapp

  vproapp:
    build:
      context: ./Docker-files/app
    image: oppytms/vproapp
    depends_on:
      - vprodb
      - vprocache01
      - vpromq01

  vprodb:
    build:
      context: ./Docker-files/db
    image: oppytms/vprodb
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - vprodb-data:/var/lib/mysql

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  vprodb-data:
