version: '3.8'
services:
  vproweb:
    build:
      context: ./Docker-files/web
    ports:
      - "80:80"
    depends_on:
      - vproapp

  vproapp:
    build:
      context: ./Docker-files/app
    depends_on:
      - vprodb
      - vprocache01
      - vpromq01

  vprodb:
    build:
      context: ./Docker-files/db
    env_file:
      - Docker-files/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${ENV_MYSQL_DATABASE}
      - MYSQL_USER=${ENV_MYSQL_USER}
      - MYSQL_PASSWORD=${ENV_MYSQL_PASSWORD}
    volumes:
      - vprodb-data:/var/lib/mysql

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  vprodb-data:
